import type { Exercise } from "@/types/domain";

/**
 * Curated MVP catalog. `slug` matches @bryllim/workout-guide entries; frame
 * illustrations are copied from the package into /public/exercises at build
 * time so they render without network access (CC BY-SA 4.0, Bryl Lim —
 * attribution shown in Settings and on the workout screens).
 */
export const EXERCISES: Exercise[] = [
  {
    id: "ex-knee-push-up",
    slug: "knee-push-up",
    name: "Knee Push-up",
    description: "A gentle push-up from the knees to build pressing strength.",
    category: "push",
    muscles: ["Chest", "Triceps"],
    difficulty: 1,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a knee push-up position",
    progression: "push-up",
    safety: "Keep a straight line from head to knees; stop if wrists or shoulders hurt.",
  },
  {
    id: "ex-incline-push-up",
    slug: "incline-push-up",
    name: "Incline Push-up",
    description: "Hands on a bench or counter to make the push-up easier.",
    category: "push",
    muscles: ["Chest", "Triceps"],
    difficulty: 1,
    equipment: ["bench"],
    measure: "reps",
    illustrationAlt: "Illustration of an incline push-up",
    regression: "knee-push-up",
    progression: "push-up",
    safety: "Use a stable surface that cannot slide.",
  },
  {
    id: "ex-push-up",
    slug: "push-up",
    name: "Push-up",
    description: "Classic floor push-up with a rigid body line.",
    category: "push",
    muscles: ["Chest", "Triceps", "Core"],
    difficulty: 2,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a push-up",
    regression: "knee-push-up",
    progression: "diamond-push-up",
    safety: "Brace your core; elbows about 45° from the body.",
  },
  {
    id: "ex-diamond-push-up",
    slug: "diamond-push-up",
    name: "Diamond Push-up",
    description: "Narrow-hand push-up that emphasizes the triceps.",
    category: "push",
    muscles: ["Triceps", "Chest"],
    difficulty: 4,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a diamond push-up",
    regression: "push-up",
    safety: "Keep wrists comfortable; shorten the range if needed.",
  },
  {
    id: "ex-pike-push-up",
    slug: "pike-push-up",
    name: "Pike Push-up",
    description: "Hips-high push-up that shifts load toward the shoulders.",
    category: "push",
    muscles: ["Shoulders", "Triceps"],
    difficulty: 3,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a pike push-up",
    regression: "push-up",
    safety: "Keep your neck neutral; look at your feet, not the floor ahead.",
  },
  {
    id: "ex-dip",
    slug: "dip",
    name: "Dip",
    description: "Parallel-bar dip for chest and triceps.",
    category: "push",
    muscles: ["Chest", "Triceps"],
    difficulty: 4,
    equipment: ["bench"],
    measure: "reps",
    illustrationAlt: "Illustration of a dip",
    regression: "bench-supported dip with feet down",
    safety: "Stop above shoulder discomfort; avoid shrugging.",
  },
  {
    id: "ex-inverted-row",
    slug: "inverted-row",
    name: "Inverted Row",
    description: "Horizontal pull under a bar or sturdy table edge.",
    category: "pull",
    muscles: ["Back", "Biceps"],
    difficulty: 2,
    equipment: ["pullup_bar"],
    measure: "reps",
    illustrationAlt: "Illustration of an inverted row",
    progression: "pull-up",
    safety: "Check the surface can hold you; keep ribs down.",
  },
  {
    id: "ex-pull-up",
    slug: "pull-up",
    name: "Pull-up",
    description: "Full hang to chin-over-bar pull.",
    category: "pull",
    muscles: ["Lats", "Biceps"],
    difficulty: 4,
    equipment: ["pullup_bar"],
    measure: "reps",
    illustrationAlt: "Illustration of a pull-up",
    regression: "inverted-row",
    safety: "Avoid kipping in the MVP program; control the lowering phase.",
  },
  {
    id: "ex-bodyweight-squat",
    slug: "bodyweight-squat",
    name: "Bodyweight Squat",
    description: "Sit back and down to a comfortable depth, drive up tall.",
    category: "squat",
    muscles: ["Quads", "Glutes"],
    difficulty: 1,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a bodyweight squat",
    progression: "bulgarian-split-squat",
    safety: "Knees track over toes; heels stay down.",
  },
  {
    id: "ex-goblet-squat",
    slug: "goblet-squat",
    name: "Goblet Squat",
    description: "Squat holding a dumbbell at the chest.",
    category: "squat",
    muscles: ["Quads", "Glutes"],
    difficulty: 2,
    equipment: ["dumbbells"],
    measure: "reps",
    illustrationAlt: "Illustration of a goblet squat",
    regression: "bodyweight-squat",
    safety: "Start light; keep the chest up.",
  },
  {
    id: "ex-bulgarian-split-squat",
    slug: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    description: "Rear-foot-elevated single-leg squat.",
    category: "squat",
    muscles: ["Quads", "Glutes"],
    difficulty: 4,
    equipment: ["bench"],
    measure: "reps",
    illustrationAlt: "Illustration of a Bulgarian split squat",
    regression: "bodyweight-squat",
    safety: "Hold a support until balance is reliable.",
  },
  {
    id: "ex-glute-bridge",
    slug: "glute-bridge",
    name: "Glute Bridge",
    description: "Hip lift from the floor for glutes and hamstrings.",
    category: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    difficulty: 1,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a glute bridge",
    progression: "single-leg-romanian-deadlift",
    safety: "Squeeze glutes at the top; do not arch the lower back.",
  },
  {
    id: "ex-good-morning",
    slug: "good-morning",
    name: "Good Morning",
    description: "Hip hinge with hands behind the head.",
    category: "hinge",
    muscles: ["Hamstrings", "Lower Back"],
    difficulty: 2,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a good morning hinge",
    regression: "glute-bridge",
    safety: "Soft knees, neutral spine, small range first.",
  },
  {
    id: "ex-single-leg-romanian-deadlift",
    slug: "single-leg-romanian-deadlift",
    name: "Single-Leg Romanian Deadlift",
    description: "One-legged hinge with a dumbbell.",
    category: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    difficulty: 4,
    equipment: ["dumbbells"],
    measure: "reps",
    illustrationAlt: "Illustration of a single-leg Romanian deadlift",
    regression: "good-morning",
    safety: "Stand near a wall or chair for balance support.",
  },
  {
    id: "ex-plank",
    slug: "plank",
    name: "Plank",
    description: "Straight-line forearm hold.",
    category: "core",
    muscles: ["Core"],
    difficulty: 2,
    equipment: ["none"],
    measure: "hold",
    illustrationAlt: "Illustration of a plank hold",
    regression: "dead-bug",
    progression: "side-plank",
    safety: "Stop if the lower back sags or pinches.",
  },
  {
    id: "ex-side-plank",
    slug: "side-plank",
    name: "Side Plank",
    description: "Lateral hold on one forearm.",
    category: "core",
    muscles: ["Obliques", "Core"],
    difficulty: 3,
    equipment: ["none"],
    measure: "hold",
    illustrationAlt: "Illustration of a side plank",
    regression: "plank",
    safety: "Stack shoulder over elbow; drop the knee to scale down.",
  },
  {
    id: "ex-dead-bug",
    slug: "dead-bug",
    name: "Dead Bug",
    description: "Alternating arm and leg reaches lying on your back.",
    category: "core",
    muscles: ["Core"],
    difficulty: 1,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a dead bug exercise",
    progression: "plank",
    safety: "Keep the lower back gently pressed to the floor.",
  },
  {
    id: "ex-bird-dog",
    slug: "bird-dog",
    name: "Bird Dog",
    description: "Opposite arm and leg reach from all fours.",
    category: "core",
    muscles: ["Core", "Glutes"],
    difficulty: 1,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of a bird dog exercise",
    progression: "plank",
    safety: "Move slowly; hips stay level.",
  },
  {
    id: "ex-mountain-climber",
    slug: "mountain-climber",
    name: "Mountain Climber",
    description: "Alternating knee drives from a plank position.",
    category: "core",
    muscles: ["Core", "Hip Flexors"],
    difficulty: 3,
    equipment: ["none"],
    measure: "reps",
    illustrationAlt: "Illustration of mountain climbers",
    regression: "plank",
    safety: "Keep wrists under shoulders; slow down if form breaks.",
  },
  {
    id: "ex-hanging-knee-raise",
    slug: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    description: "Knee lifts while hanging from a bar.",
    category: "core",
    muscles: ["Core", "Grip"],
    difficulty: 3,
    equipment: ["pullup_bar"],
    measure: "reps",
    illustrationAlt: "Illustration of a hanging knee raise",
    regression: "dead-bug",
    safety: "No swinging; step down if grip fails.",
  },
  {
    id: "ex-superman-hold",
    slug: "superman-hold",
    name: "Superman Hold",
    description: "Prone back-extension hold.",
    category: "core",
    muscles: ["Lower Back", "Glutes"],
    difficulty: 1,
    equipment: ["none"],
    measure: "hold",
    illustrationAlt: "Illustration of a superman hold",
    safety: "Lift gently; stop on any back pain.",
  },
];

export function exerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function exerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find((e) => e.slug === slug);
}
